import os
from concurrent.futures import ThreadPoolExecutor

from dotenv import load_dotenv
from pydantic import BaseModel, Field, field_validator

from ingestion.embeddings import get_embeddings
from llm.bedrock_llm import get_structured_completion
from vectorstore.opensearch_store import OpenSearchVectorStore, Retriever

load_dotenv()

NULL_STRINGS = {"null", "none", "n/a", "na", "not available", "unavailable", "not found", ""}


class FinancialMetrics(BaseModel):
    revenue: str | None = Field(None, description="Total net sales / revenue, with currency and unit, e.g. '$391,035 million'")
    net_income: str | None = Field(None, description="Net income, with currency and unit")
    operating_income: str | None = Field(None, description="Operating income, with currency and unit")
    cash_flow: str | None = Field(None, description="Cash generated by (or provided by) operating activities, with currency and unit")
    total_assets: str | None = Field(None, description="Total assets from the balance sheet, with currency and unit")
    total_liabilities: str | None = Field(None, description="Total liabilities from the balance sheet, with currency and unit")
    risk_factors: list[str] | None = Field(None, description="3-5 concise top risk factors")
    growth_drivers: list[str] | None = Field(None, description="3-5 concise top growth drivers")

    @field_validator("*", mode="before")
    @classmethod
    def clean_nulls(cls, v):
        """Turn 'null'-like strings into real None so the UI shows a dash."""
        if isinstance(v, (int, float)):
            return str(v)
        if isinstance(v, str) and v.strip().lower() in NULL_STRINGS:
            return None
        if isinstance(v, list):
            items = [x for x in v if not (isinstance(x, str) and x.strip().lower() in NULL_STRINGS)]
            return items or None
        return v


# One query per financial statement / topic, so each one is retrieved explicitly
CONTEXT_QUERIES = {
    "income statement": "consolidated statements of operations total net sales operating income net income",
    "balance sheet": "consolidated balance sheets total assets total liabilities shareholders equity",
    "cash flow": "consolidated statements of cash flows cash generated by operating activities",
    "risks": "risk factors that could materially affect business financial condition results",
    "growth": "drivers of net sales growth products services segments performance",
}


def _search_topic(retriever: Retriever, company: str, year: int | None, k_per_query: int,
                  topic: str, query: str) -> tuple[str, list]:
    """Run a single topic's search. Returns (topic, docs) so the caller can tell results apart."""
    docs = retriever.search(query=f"{query} {company} {year or ''}", company=company, year=year, k=k_per_query)
    return topic, docs


def retrieve_context(retriever: Retriever, company: str, year: int | None, k_per_query: int = 8) -> str:
    """Run the 5 topic searches concurrently (independent network calls; ~5x faster than sequential)."""
    with ThreadPoolExecutor(max_workers=len(CONTEXT_QUERIES)) as pool:
        results = pool.map(
            lambda item: _search_topic(retriever, company, year, k_per_query, *item),
            CONTEXT_QUERIES.items(),
        )

        seen, sections = set(), []
        for topic, docs in results:
            for doc in docs:
                key = (doc.metadata["source_file"], doc.metadata["chunk_id"])
                if key not in seen:
                    seen.add(key)
                    sections.append(f"[{topic}]\n{doc.page_content}")
    return "\n\n---\n\n".join(sections)


def build_extraction_prompt(company: str, year: int | None, context: str) -> str:
    return f"""
You are an expert financial analyst extracting figures from {company}'s annual report for fiscal year {year}.

Context (excerpts grouped by topic):
{context}

Extract:
1. Revenue (total net sales)
2. Net income
3. Operating income
4. Cash flow from operating activities (may be labelled "cash generated by operating activities")
5. Total assets
6. Total liabilities
7. Top risk factors (3-5, concise)
8. Top growth drivers (3-5, concise)

Rules:
- Use only the context above. Use the figure for fiscal year {year}, not prior years.
- Copy figures exactly, and include currency and unit (e.g. "$391,035 million"); tables often state "(In millions)".
- If a value is not in the context, leave it empty (null). Never guess.
"""


def extract_financial_metrics(retriever: Retriever, company: str, year: int | None) -> dict:
    """Extract KPIs using RAG: targeted retrieval, then LLM structured output."""
    context = retrieve_context(retriever=retriever, company=company, year=year)
    prompt = build_extraction_prompt(company=company, year=year, context=context)
    metrics = get_structured_completion(prompt=prompt, response_model=FinancialMetrics)
    return metrics.model_dump()


def main() -> None:
    company, year = "Apple", 2024

    embeddings = get_embeddings()
    store = OpenSearchVectorStore(
        endpoint=os.environ["OPENSEARCH_ENDPOINT"],
        index_name=os.getenv("OPENSEARCH_INDEX_NAME", "investor-docs"),
        region=os.getenv("AWS_REGION", "us-east-1"),
        service=os.getenv("OPENSEARCH_SERVICE", "es"),
    )
    retriever = Retriever(store.client, store.index_name, embeddings)

    results = extract_financial_metrics(retriever=retriever, company=company, year=year)

    print(f"\nExtracted KPIs for {company} {year}\n")
    for key, value in results.items():
        print(f"{key}:\n{value}\n" + "-" * 80)

    try:
        from database.save_metrics import save_metrics
        save_metrics(company=company, year=year, metrics=results)
        print("Saved to PostgreSQL")
    except ImportError:
        print("database/ not set up yet; skipping save to PostgreSQL")


if __name__ == "__main__":
    main()